FROM php:7.2-apache

RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
      git \
          zip \
	      unzip \
	        && rm -rf /var/lib/apt/lists

		# Enable PHP extensions
		RUN docker-php-ext-install pdo_mysql mysqli

		# Install composer
		RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer

		# Add cake and composer command to system path
		ENV PATH="${PATH}:/var/www/html/lib/Cake/Console"
		ENV PATH="${PATH}:/var/www/html/app/Vendor/bin"

		# COPY apache site.conf file
		COPY ./docker/apache/site.conf /etc/apache2/sites-available/000-default.conf

		# Copy the source code into /var/www/html/ inside the image
		COPY . .

		# Set default working directory
		WORKDIR ./app
