version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8005:80
    depends_on:
      - sqldata
  db:
     image: mysql:5
     volumes:
      - db-data:/var/lib/mysql
     environment:
      MYSQL_DATABASE: cakephp_db
      MYSQL_ROOT_PASSWORD: root_password

  sqldata:
     image: microsoft/mssql-server-linux:2017-latest
     environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
     ports:
      - 5434:1433
volumes:
  db-data:
      external: false
