version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8005:80
    depends_on:
      - db
  db:
     image: mysql:5
     volumes:
      - db-data:/var/lib/mysql
     environment:
      MYSQL_DATABASE: cakephp_db
      MYSQL_ROOT_PASSWORD: root_password
volumes:
  db-data:
      external: false
